### ISSUE TITLE
Front-end redesign

### ISSUE THREAD

**Issue by nsjames** [EOSPortal/eosportal-front#17]

**Comment by kesar** [comment]
<img width="251" alt="screen shot 2018-05-22 at 15 50 31" src="https://user-images.githubusercontent.com/1288106/40366632-e4aa59c0-5dd7-11e8-836a-82c9355afbfd.png">

Not sure if its final colors, but I would suggest to make it a bit less dark text / buttons. People with vision problems are not gonna see anything. 

https://uxdesign.cc/the-easiest-part-about-designing-accessible-websites-76cd6b9a7ae4

http://contrast-ratio.com/#%23294b5e-on-%23071d29
