### ISSUE TITLE
Chain Info

### ISSUE THREAD

**Issue by nsjames** [EOSPortal/eosportal-front#25]
- [x] How many BPs are allowed
- [x] How many BPs are connected ( producing or not )
- [x] Booted Date
- [x] Total Voters
- [x] Voter Percentage
- [x] Total blocks produced
- [x] Chain health

**Comment by nsjames** [comment]
- Chain health 
Grab blocks from N time in the past and check if it matches the assumed amount of blocks per second

**Comment by sogasg** [comment]
How do I get information about:
1. How many BPs are allowed
2. Total votes (number of tokens used for voting on a specific chain)

**Comment by kesar** [comment]
done
