### ISSUE TITLE
eosromania22 is showing in Greece

### ISSUE THREAD

**Issue by oviwankenobi** [EOSPortal/eosportal-front#58]
hi looking at 
http://eosportal.io/chain/12/producers
it shows eosromania22 in Greece
that's wrong, where is pulling that info from?

**Comment by kesar** [comment]
its from the regprod()  last param, location. it defaults to 0 and you must have a different number.

List of country - codes can be found here: https://gist.github.com/kesar/de2a21d975f0d410218dcd1bf94b301a

👍

**Comment by oviwankenobi** [comment]
last param for regproducer I thought is a HHMM format, hours am minutes

**Comment by kesar** [comment]
> last param for regproducer I thought is a HHMM format, hours am minutes with possibility to precede it by minus operator "-" eg -0500 for GMT-5

Unfortunately it doesn't support negatives, so we took the  ISO 3166-1 for countries ( https://en.wikipedia.org/wiki/ISO_3166-1 )

**Comment by oviwankenobi** [comment]
who's we?
is the eos platform giving to this param the same interpretation as you?

**Comment by kesar** [comment]
> who's we?

Good question, it's what EOSPortal suggested, and it's being implemented for 20 out of top 50 current BP candidates. 

We thought in the beginning about the timezone, but as I mentioned it wasnt possible. If there is a strong consensus for a better implementations I would be happy changing it. 👍

**Comment by oviwankenobi** [comment]
hmmm I just saw it now in the code
uint16_t location
it is unsigned

ok, so far I thought the interpretation is the gmt.
